### ISSUE TITLE
Differences between full and lite?

### ISSUE THREAD

**Issue by zhimin-z** [Re-Align/just-eval#2]
![image](https://github.com/Re-Align/just-eval/assets/8592144/a2bb6c5f-3fcf-463c-9eb7-38a9c9746faa)

**Comment by yuchenlin** [comment]
we wanted to provide a smaller subset like about 300 examples for people who want to do a quicker and cheaper evaluation of their models, but the current codebase has not supported it in the evaluation stage yet. we will update it soon here.  If you already have the full evaluation results and wanna only look at the lite version, then this is the relevant code: https://github.com/Re-Align/just-eval/blob/05d6e58255e7ada23dc527addd9a7f4cf2d2d895/leaderboard/scripts/show_tables.py#L19

**Comment by yuchenlin** [comment]
also, we're doing a gpt-4-turbo version for the evaluation, plz stay tuned
